# Generated by Django 5.1.1 on 2024-10-09 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('combustion', 'Combustion'), ('electric', 'Electric'), ('plug-in-hybrid', 'Hybrid')], max_length=16, verbose_name='Engine Type')),
            ],
            options={
                'verbose_name': 'Car Expense',
                'verbose_name_plural': 'Car Expenses',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('car_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='reimbursements.cartrip', verbose_name='Car Trip')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('course', 'Course'), ('committee', 'Committee')], max_length=16, verbose_name='Type')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.person', verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Reimbursement',
                'verbose_name_plural': 'Reimbursements',
            },
        ),
        migrations.CreateModel(
            name='GenericExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('purpose', models.CharField(max_length=255, verbose_name='Purpose')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('reimbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic', to='reimbursements.reimbursement', verbose_name='Reimbursement')),
            ],
            options={
                'verbose_name': 'Generic Expense',
                'verbose_name_plural': 'Generic Expenses',
                'ordering': ['reimbursement', 'date'],
            },
        ),
        migrations.CreateModel(
            name='FoodExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('absence', models.CharField(choices=[('full', 'Full Day'), ('travel', 'Travel Day'), ('single', 'Single Day')], max_length=8, verbose_name='Absence')),
                ('breakfast', models.BooleanField(verbose_name='Breakfast')),
                ('lunch', models.BooleanField(verbose_name='Lunch')),
                ('dinner', models.BooleanField(verbose_name='Dinner')),
                ('reimbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='reimbursements.reimbursement', verbose_name='Reimbursement')),
            ],
            options={
                'verbose_name': 'Food Expense',
                'verbose_name_plural': 'Food Expenses',
                'ordering': ['reimbursement', 'date'],
            },
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.course', verbose_name='Course')),
                ('reimbursement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_details', to='reimbursements.reimbursement', verbose_name='Reimbursement')),
            ],
            options={
                'verbose_name': 'Course Reimbursement',
                'verbose_name_plural': 'Course Reimbursements',
            },
        ),
        migrations.CreateModel(
            name='TransportExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('onsite', 'On Site')], max_length=8, verbose_name='Direction')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('origin', models.CharField(max_length=255, verbose_name='Origin')),
                ('destination', models.CharField(max_length=255, verbose_name='Destination')),
                ('mode', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('public', 'Public Transport'), ('plan', 'Public Transport Plan')], max_length=8, verbose_name='Transport Mode')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Distance')),
                ('reimbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='reimbursements.reimbursement', verbose_name='Reimbursement')),
            ],
            options={
                'verbose_name': 'Transport Expense',
                'verbose_name_plural': 'Transport Expenses',
                'ordering': ['reimbursement', 'direction', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('discount', models.CharField(choices=[('BC25', 'Bahn Card 25'), ('BC50', 'Bahn Card 50'), ('none', 'No Discount')], max_length=4, verbose_name='Discount')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reimbursements.transportexpense', verbose_name='Transport Expense')),
            ],
            options={
                'verbose_name': 'Train Expense',
                'verbose_name_plural': 'Train Expenses',
            },
        ),
        migrations.AddField(
            model_name='cartrip',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_trip', to='reimbursements.transportexpense', verbose_name='Transport Expense'),
        ),
        migrations.CreateModel(
            name='TravelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255, verbose_name='Purpose')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('reimbursement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_details', to='reimbursements.reimbursement', verbose_name='Reimbursement')),
            ],
            options={
                'verbose_name': 'Travel Details',
                'verbose_name_plural': 'Travel Details',
            },
        ),
    ]
