# Generated by Django 5.1.1 on 2024-09-24 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_admin_provided', models.BooleanField(default=False, verbose_name='Is Admin Provided')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_info.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Localities',
                'unique_together': {('postal_code', 'name', 'country')},
            },
        ),
    ]
