# Generated by Django 5.1.1 on 2024-09-23 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_admin_provided', models.BooleanField(default=False, verbose_name='Is Admin Provided')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_info.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Localities',
                'unique_together': {('postal_code', 'name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255, verbose_name='Line 1')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Line 2')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contact_info.contact', verbose_name='Contact')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_info.locality', verbose_name='Locality')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, unique=True, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='contact_info.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
            },
        ),
    ]
