# Generated by Django 5.1.5 on 2025-01-21 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Course Year',
                'verbose_name_plural': 'Course Years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Course Number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('GA', 'Basic Training'), ('FB', 'Continuing Training'), ('AM', 'Advanced Training'), ('JV', 'Youth Assembly'), ('SV', 'Special Event')], max_length=255, verbose_name='Course Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sections.federation', verbose_name='Federation')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.courseyear', verbose_name='Course Year')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['federation', '-end_date', '-number'],
            },
        ),
    ]
