# Generated by Django 5.1.1 on 2024-09-12 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'National Federation'), (1, 'State Federation'), (2, 'District Federation')], verbose_name='Level')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sections.federation', verbose_name='Parent')),
            ],
            options={
                'ordering': ['type', 'name'],
                'verbose_name': 'Federation',
                'verbose_name_plural': 'Federations',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Section Number')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_section_set', to='sections.federation', verbose_name='District Federation')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_section_set', to='sections.federation', verbose_name='State Federation')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
