# Generated by Django 5.1.1 on 2024-10-06 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_info', '0001_initial'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=255, verbose_name='Given Name')),
                ('family_name', models.CharField(max_length=255, verbose_name='Family Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255, verbose_name='Line 1')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Line 2')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_info.locality', verbose_name='Locality')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='people.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Person Address',
                'verbose_name_plural': 'Person Addresses',
            },
        ),
        migrations.CreateModel(
            name='PersonBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='people.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Person Bank Account',
                'verbose_name_plural': 'Person Bank Accounts',
            },
        ),
    ]
