# Generated by Django 5.1.1 on 2024-09-22 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_info', '0001_initial'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contact_info.contact')),
                ('given_name', models.CharField(max_length=255, verbose_name='Given Name')),
                ('family_name', models.CharField(max_length=255, verbose_name='Family Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.section', verbose_name='Section')),
            ],
            bases=('contact_info.contact',),
        ),
    ]
